AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: policy-cancellation-sam with Cognito scopes

Globals:
  Function:
    Timeout: 5
    LoggingConfig:
      LogFormat: JSON

Resources:
  ############################
  # Cognito User Pool
  ############################
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: policy-cancellation-user-pool
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email

  ############################
  # Cognito Resource Server
  ############################
  PolicyResourceServer:
    Type: AWS::Cognito::UserPoolResourceServer
    Properties:
      UserPoolId: !Ref UserPool
      Identifier: policy-api
      Name: PolicyCancellationAPI
      Scopes:
        - ScopeName: cancel
          ScopeDescription: Cancel a policy
        - ScopeName: read
          ScopeDescription: Read policy details

  ############################
  # Cognito App Client
  ############################
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: policy-cancellation-client
      UserPoolId: !Ref UserPool
      GenerateSecret: true
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - client_credentials
      AllowedOAuthScopes:
        - policy-api/cancel
        - policy-api/read
      SupportedIdentityProviders:
        - COGNITO

  ############################
  # API Gateway
  ############################
  PolicyCancellationApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: policy-cancellation-api
      StageName: Prod
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt UserPool.Arn

  ############################
  # Lambda Function
  ############################
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      FunctionName: policy-cancellation
      Architectures:
        - x86_64
      Policies:
        - S3WritePolicy:
            BucketName: policy-cancellation-payloads
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId: !Ref PolicyCancellationApi
            Path: /hello
            Method: post
            Auth:
              Authorizer: CognitoAuthorizer
              AuthorizationScopes:
                - policy-api/cancel

############################
# Outputs
############################
Outputs:
  ApiUrl:
    Description: Protected API endpoint
    Value: !Sub "https://${PolicyCancellationApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"

  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool

  UserPoolClientId:
    Description: Cognito App Client ID
    Value: !Ref UserPoolClient
